version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: nest_user_service
    environment:
      POSTGRES_DB: nest_user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: